FROM keymetrics/pm2:8-alpine

WORKDIR /xapi-service

COPY . /xapi-service

# https://github.com/kelektiv/node.bcrypt.js/wiki/Installation-Instructions#docker
RUN apk --no-cache add --virtual builds-deps build-base python

ENTRYPOINT ["yarn"]
